// Lighting Profiles for Perspective Room — Un Autre Regard
// Each profile ID matches ApproachConfig.key exactly

class LightingProfile {
  final String id;
  final String label;
  final String group;
  final int backgroundColor;
  final List<int> animatedGradient;
  final int textColor;
  final int accentColor;
  final String fontFamilyTitle;
  final String fontFamilyBody;
  final MotionProfile motion;
  final EntranceProfile entrance;

  const LightingProfile({
    required this.id,
    required this.label,
    required this.group,
    required this.backgroundColor,
    required this.animatedGradient,
    required this.textColor,
    required this.accentColor,
    required this.fontFamilyTitle,
    required this.fontFamilyBody,
    required this.motion,
    required this.entrance,
  });
}

class MotionProfile {
  final String type;
  final double periodSeconds;
  const MotionProfile({required this.type, required this.periodSeconds});
}

class EntranceProfile {
  final String type;
  final int staggerMs;
  const EntranceProfile({required this.type, required this.staggerMs});
}

/// Default fallback profile for unknown sources
const LightingProfile kDefaultLightingProfile = LightingProfile(
  id: 'default',
  label: 'Perspective',
  group: 'default',
  backgroundColor: 0xFF1F2937,
  animatedGradient: [0xFF1F2937, 0xFF111827],
  textColor: 0xFFF9FAFB,
  accentColor: 0xFF60A5FA,
  fontFamilyTitle: 'Inter',
  fontFamilyBody: 'Inter',
  motion: MotionProfile(type: 'soft_drift', periodSeconds: 30.0),
  entrance: EntranceProfile(type: 'layer_fade', staggerMs: 100),
);

/// All lighting profiles indexed by ApproachConfig.key
const Map<String, LightingProfile> kLightingProfilesMap = {
  // ========================================
  // SOURCES SPIRITUELLES
  // ========================================
  'judaisme_rabbinique': LightingProfile(
    id: 'judaisme_rabbinique',
    label: 'Judaïsme rabbinique',
    group: 'spiritual',
    backgroundColor: 0xFFF6F1E8,
    animatedGradient: [0xFFF6F1E8, 0xFFF0E6D8],
    textColor: 0xFF1E1A14,
    accentColor: 0xFFB89B5E,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'vertical_glow', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'moussar': LightingProfile(
    id: 'moussar',
    label: 'Moussar',
    group: 'spiritual',
    backgroundColor: 0xFFF3EBDD,
    animatedGradient: [0xFFF3EBDD, 0xFFEAD9C0],
    textColor: 0xFF1E1A14,
    accentColor: 0xFF8B6B3F,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'still', periodSeconds: 40.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'kabbale': LightingProfile(
    id: 'kabbale',
    label: 'Kabbale',
    group: 'spiritual',
    backgroundColor: 0xFF0E1A2B,
    animatedGradient: [0xFF0E1A2B, 0xFF142B4A],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFD9C17A,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'pulse_depth', periodSeconds: 22.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'christianisme': LightingProfile(
    id: 'christianisme',
    label: 'Christianisme',
    group: 'spiritual',
    backgroundColor: 0xFFF7F2E7,
    animatedGradient: [0xFFF7F2E7, 0xFFEFE4D3],
    textColor: 0xFF1E1A14,
    accentColor: 0xFFC9A86A,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'lift_light', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'islam': LightingProfile(
    id: 'islam',
    label: 'Islam',
    group: 'spiritual',
    backgroundColor: 0xFF0F2B1F,
    animatedGradient: [0xFF0F2B1F, 0xFF164236],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF8ED1B2,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'cycle_arc', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'soufisme': LightingProfile(
    id: 'soufisme',
    label: 'Soufisme',
    group: 'spiritual',
    backgroundColor: 0xFF141A3A,
    animatedGradient: [0xFF141A3A, 0xFF242C66],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFA6B7FF,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'sway', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'bouddhisme': LightingProfile(
    id: 'bouddhisme',
    label: 'Bouddhisme',
    group: 'spiritual',
    backgroundColor: 0xFFF2F2F0,
    animatedGradient: [0xFFF2F2F0, 0xFFE6E6E0],
    textColor: 0xFF1E1E1E,
    accentColor: 0xFF9AA0A6,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'still', periodSeconds: 60.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'hindouisme': LightingProfile(
    id: 'hindouisme',
    label: 'Hindouisme',
    group: 'spiritual',
    backgroundColor: 0xFFF6E4C9,
    animatedGradient: [0xFFF6E4C9, 0xFFF0C98A],
    textColor: 0xFF2A1B0E,
    accentColor: 0xFFB0562A,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Literata',
    motion: MotionProfile(type: 'cycle_mandala', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'spiritualite_contemporaine': LightingProfile(
    id: 'spiritualite_contemporaine',
    label: 'Spiritualité contemporaine',
    group: 'spiritual',
    backgroundColor: 0xFFEFEFEF,
    animatedGradient: [0xFFEFEFEF, 0xFFE7E3DD],
    textColor: 0xFF202124,
    accentColor: 0xFF6B7280,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'soft_drift', periodSeconds: 34.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),

  // ========================================
  // COURANTS LITTÉRAIRES
  // ========================================
  'romantisme': LightingProfile(
    id: 'romantisme',
    label: 'Romantisme',
    group: 'literary',
    backgroundColor: 0xFF1C1326,
    animatedGradient: [0xFF1C1326, 0xFF3A214D],
    textColor: 0xFFF7F3FF,
    accentColor: 0xFFFF9BD1,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'mist', periodSeconds: 22.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'realisme': LightingProfile(
    id: 'realisme',
    label: 'Réalisme',
    group: 'literary',
    backgroundColor: 0xFFECE6DE,
    animatedGradient: [0xFFECE6DE, 0xFFE3D6C7],
    textColor: 0xFF2E2E2E,
    accentColor: 0xFF9C6B3D,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'horizontal_drift', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'naturalisme': LightingProfile(
    id: 'naturalisme',
    label: 'Naturalisme',
    group: 'literary',
    backgroundColor: 0xFF1E2A24,
    animatedGradient: [0xFF1E2A24, 0xFF2B3D33],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF8FBF9F,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'grain_scroll', periodSeconds: 30.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'symbolisme': LightingProfile(
    id: 'symbolisme',
    label: 'Symbolisme',
    group: 'literary',
    backgroundColor: 0xFF241B2F,
    animatedGradient: [0xFF241B2F, 0xFF3B2A50],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFBFA6FF,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'fade_in_out', periodSeconds: 18.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'surrealisme': LightingProfile(
    id: 'surrealisme',
    label: 'Surréalisme',
    group: 'literary',
    backgroundColor: 0xFF0B1E2D,
    animatedGradient: [0xFF0B1E2D, 0xFF163C57],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF66E3FF,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'liquid_warp', periodSeconds: 16.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'existentialisme': LightingProfile(
    id: 'existentialisme',
    label: 'Existentialisme',
    group: 'literary',
    backgroundColor: 0xFF0E1A2B,
    animatedGradient: [0xFF0E1A2B, 0xFF111827],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF6FA3FF,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'oscillation', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'humanisme': LightingProfile(
    id: 'humanisme',
    label: 'Humanisme',
    group: 'literary',
    backgroundColor: 0xFFFFF7E6,
    animatedGradient: [0xFFFFF7E6, 0xFFFDE3B0],
    textColor: 0xFF2A2218,
    accentColor: 0xFFE08A00,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'sunrise', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'absurdisme': LightingProfile(
    id: 'absurdisme',
    label: 'Absurdisme',
    group: 'literary',
    backgroundColor: 0xFF111111,
    animatedGradient: [0xFF111111, 0xFF2B2B2B],
    textColor: 0xFFF5F5F5,
    accentColor: 0xFFFFD166,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'glitch_soft', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'modernisme': LightingProfile(
    id: 'modernisme',
    label: 'Modernisme',
    group: 'literary',
    backgroundColor: 0xFFF3F4F6,
    animatedGradient: [0xFFF3F4F6, 0xFFD1D5DB],
    textColor: 0xFF111827,
    accentColor: 0xFF2563EB,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'grid_parallax', periodSeconds: 30.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'postmodernisme': LightingProfile(
    id: 'postmodernisme',
    label: 'Postmodernisme',
    group: 'literary',
    backgroundColor: 0xFF1F2937,
    animatedGradient: [0xFF1F2937, 0xFF0B1220],
    textColor: 0xFFF9FAFB,
    accentColor: 0xFFF472B6,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'layer_shuffle_slow', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'tragedie_classique': LightingProfile(
    id: 'tragedie_classique',
    label: 'Tragédie classique',
    group: 'literary',
    backgroundColor: 0xFF120C10,
    animatedGradient: [0xFF120C10, 0xFF2A1220],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFE11D48,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'curtain', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'roman_psychologique': LightingProfile(
    id: 'roman_psychologique',
    label: 'Roman psychologique',
    group: 'literary',
    backgroundColor: 0xFF2A1F1A,
    animatedGradient: [0xFF2A1F1A, 0xFF3B2A22],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFF59E0B,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'breath', periodSeconds: 22.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'mythologie': LightingProfile(
    id: 'mythologie',
    label: 'Mythologie',
    group: 'literary',
    backgroundColor: 0xFF07070A,
    animatedGradient: [0xFF07070A, 0xFF1C1C28],
    textColor: 0xFFF7F3E8,
    accentColor: 0xFFD4AF37,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'torch_flicker_slow', periodSeconds: 18.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'science_fiction': LightingProfile(
    id: 'science_fiction',
    label: 'Science-fiction',
    group: 'literary',
    backgroundColor: 0xFF051827,
    animatedGradient: [0xFF051827, 0xFF0B3A5A],
    textColor: 0xFFE6F6FF,
    accentColor: 0xFF22D3EE,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'starfield_slow', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'fantasy': LightingProfile(
    id: 'fantasy',
    label: 'Fantasy',
    group: 'literary',
    backgroundColor: 0xFF0B2A1A,
    animatedGradient: [0xFF0B2A1A, 0xFF1A4D2E],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFA7F3D0,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'fireflies', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'poetique': LightingProfile(
    id: 'poetique',
    label: 'Poétique',
    group: 'literary',
    backgroundColor: 0xFF1A1625,
    animatedGradient: [0xFF1A1625, 0xFF2D2440],
    textColor: 0xFFF7F3FF,
    accentColor: 0xFFE879F9,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'breath', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),
  'mystique': LightingProfile(
    id: 'mystique',
    label: 'Mystique',
    group: 'literary',
    backgroundColor: 0xFF0D1117,
    animatedGradient: [0xFF0D1117, 0xFF1C1F26],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFA78BFA,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'pulse_depth', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'symboliste_moderne': LightingProfile(
    id: 'symboliste_moderne',
    label: 'Symboliste moderne',
    group: 'literary',
    backgroundColor: 0xFF1E1B2E,
    animatedGradient: [0xFF1E1B2E, 0xFF2E2A48],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF818CF8,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'fade_in_out', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_slide_fade', staggerMs: 110),
  ),

  // ========================================
  // APPROCHES PSYCHOLOGIQUES
  // ========================================
  'act': LightingProfile(
    id: 'act',
    label: 'ACT',
    group: 'psychological',
    backgroundColor: 0xFFEAF7F0,
    animatedGradient: [0xFFEAF7F0, 0xFFD7F0E3],
    textColor: 0xFF0F2B1F,
    accentColor: 0xFF34D399,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'breath', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'section_reveal', staggerMs: 100),
  ),
  'tcc': LightingProfile(
    id: 'tcc',
    label: 'TCC',
    group: 'psychological',
    backgroundColor: 0xFFEEF6FF,
    animatedGradient: [0xFFEEF6FF, 0xFFDCEBFF],
    textColor: 0xFF0B1220,
    accentColor: 0xFF3B82F6,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'still', periodSeconds: 36.0),
    entrance: EntranceProfile(type: 'stepper_reveal', staggerMs: 100),
  ),
  'jungienne': LightingProfile(
    id: 'jungienne',
    label: 'Jungienne',
    group: 'psychological',
    backgroundColor: 0xFF1B1526,
    animatedGradient: [0xFF1B1526, 0xFF2F2450],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFA78BFA,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'shadow_reveal', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 100),
  ),
  'logotherapie': LightingProfile(
    id: 'logotherapie',
    label: 'Logothérapie',
    group: 'psychological',
    backgroundColor: 0xFF0B1E2D,
    animatedGradient: [0xFF0B1E2D, 0xFF123B55],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFFDE68A,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'horizon', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'section_reveal', staggerMs: 100),
  ),
  'schemas_young': LightingProfile(
    id: 'schemas_young',
    label: 'Schémas (Young)',
    group: 'psychological',
    backgroundColor: 0xFFF7F1FF,
    animatedGradient: [0xFFF7F1FF, 0xFFE9D5FF],
    textColor: 0xFF2A1B3D,
    accentColor: 0xFF8B5CF6,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'layers_stack_slow', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'section_reveal', staggerMs: 100),
  ),
  'the_work': LightingProfile(
    id: 'the_work',
    label: 'The Work',
    group: 'psychological',
    backgroundColor: 0xFFFAFAF7,
    animatedGradient: [0xFFFAFAF7, 0xFFF1F5F9],
    textColor: 0xFF111827,
    accentColor: 0xFF64748B,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'still', periodSeconds: 60.0),
    entrance: EntranceProfile(type: 'question_tick', staggerMs: 100),
  ),
  'humaniste_rogers': LightingProfile(
    id: 'humaniste_rogers',
    label: 'Humaniste (Rogers)',
    group: 'psychological',
    backgroundColor: 0xFFFFF7ED,
    animatedGradient: [0xFFFFF7ED, 0xFFFFE4C7],
    textColor: 0xFF2A2218,
    accentColor: 0xFFFB923C,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'warm_glow', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'section_reveal', staggerMs: 100),
  ),
  'psychanalyse': LightingProfile(
    id: 'psychanalyse',
    label: 'Psychanalyse',
    group: 'psychological',
    backgroundColor: 0xFF2B1D1A,
    animatedGradient: [0xFF2B1D1A, 0xFF120C10],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFF97316,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'pulse_depth', periodSeconds: 22.0),
    entrance: EntranceProfile(type: 'section_reveal', staggerMs: 100),
  ),
  'analyse_transactionnelle': LightingProfile(
    id: 'analyse_transactionnelle',
    label: 'Analyse Transactionnelle',
    group: 'psychological',
    backgroundColor: 0xFFF0F9FF,
    animatedGradient: [0xFFF0F9FF, 0xFFD9F2FF],
    textColor: 0xFF0B1220,
    accentColor: 0xFF06B6D4,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'triads', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'section_reveal', staggerMs: 100),
  ),
  'systemique': LightingProfile(
    id: 'systemique',
    label: 'Systémique',
    group: 'psychological',
    backgroundColor: 0xFFE7F6FF,
    animatedGradient: [0xFFE7F6FF, 0xFFCDEBFF],
    textColor: 0xFF0B1220,
    accentColor: 0xFF22C55E,
    fontFamilyTitle: 'Inter',
    fontFamilyBody: 'Inter',
    motion: MotionProfile(type: 'orbit_slow', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'section_reveal', staggerMs: 100),
  ),

  // ========================================
  // COURANTS PHILOSOPHIQUES
  // ========================================
  'stoicisme': LightingProfile(
    id: 'stoicisme',
    label: 'Stoïcisme',
    group: 'philosophical',
    backgroundColor: 0xFFE8EFEA,
    animatedGradient: [0xFFE8EFEA, 0xFFD7E5DD],
    textColor: 0xFF1F2D26,
    accentColor: 0xFF3F6B55,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'still', periodSeconds: 60.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'stoicisme_philo': LightingProfile(
    id: 'stoicisme_philo',
    label: 'Stoïcisme',
    group: 'philosophical',
    backgroundColor: 0xFFE8EFEA,
    animatedGradient: [0xFFE8EFEA, 0xFFD7E5DD],
    textColor: 0xFF1F2D26,
    accentColor: 0xFF3F6B55,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'still', periodSeconds: 60.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'epicurisme': LightingProfile(
    id: 'epicurisme',
    label: 'Épicurisme',
    group: 'philosophical',
    backgroundColor: 0xFFEAF2FF,
    animatedGradient: [0xFFEAF2FF, 0xFFD8E7FF],
    textColor: 0xFF0B1220,
    accentColor: 0xFF60A5FA,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'soft_drift', periodSeconds: 34.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'existentialisme_philo': LightingProfile(
    id: 'existentialisme_philo',
    label: 'Existentialisme',
    group: 'philosophical',
    backgroundColor: 0xFF0E1A2B,
    animatedGradient: [0xFF0E1A2B, 0xFF111827],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF6FA3FF,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'oscillation', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'phenomenologie': LightingProfile(
    id: 'phenomenologie',
    label: 'Phénoménologie',
    group: 'philosophical',
    backgroundColor: 0xFF0B1220,
    animatedGradient: [0xFF0B1220, 0xFF111827],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFA3E635,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'focus_pull', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'absurdisme_philo': LightingProfile(
    id: 'absurdisme_philo',
    label: 'Absurdisme',
    group: 'philosophical',
    backgroundColor: 0xFF111111,
    animatedGradient: [0xFF111111, 0xFF2B2B2B],
    textColor: 0xFFF5F5F5,
    accentColor: 0xFFFFD166,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'glitch_soft', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'rationalisme': LightingProfile(
    id: 'rationalisme',
    label: 'Rationalisme',
    group: 'philosophical',
    backgroundColor: 0xFFF5F7FA,
    animatedGradient: [0xFFF5F7FA, 0xFFE2E8F0],
    textColor: 0xFF0B1220,
    accentColor: 0xFF475569,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'grid_parallax', periodSeconds: 38.0),
    entrance: EntranceProfile(type: 'stepper_reveal', staggerMs: 120),
  ),
  'empirisme': LightingProfile(
    id: 'empirisme',
    label: 'Empirisme',
    group: 'philosophical',
    backgroundColor: 0xFFEEF2F7,
    animatedGradient: [0xFFEEF2F7, 0xFFE2E8F0],
    textColor: 0xFF0B1220,
    accentColor: 0xFF38BDF8,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'raindrop_slow', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'idealisme': LightingProfile(
    id: 'idealisme',
    label: 'Idéalisme',
    group: 'philosophical',
    backgroundColor: 0xFFF7F2FF,
    animatedGradient: [0xFFF7F2FF, 0xFFE9D5FF],
    textColor: 0xFF2A1B3D,
    accentColor: 0xFFC4B5FD,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'float_up', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'pragmatisme': LightingProfile(
    id: 'pragmatisme',
    label: 'Pragmatisme',
    group: 'philosophical',
    backgroundColor: 0xFFFFF7E6,
    animatedGradient: [0xFFFFF7E6, 0xFFFDE3B0],
    textColor: 0xFF2A2218,
    accentColor: 0xFFF97316,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'snap_settle_slow', periodSeconds: 22.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'vitalisme': LightingProfile(
    id: 'vitalisme',
    label: 'Vitalisme',
    group: 'philosophical',
    backgroundColor: 0xFF1B1A11,
    animatedGradient: [0xFF1B1A11, 0xFF2A2A18],
    textColor: 0xFFF7F3E8,
    accentColor: 0xFFF59E0B,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'pulse_heat', periodSeconds: 18.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'humanisme_philo': LightingProfile(
    id: 'humanisme_philo',
    label: 'Humanisme',
    group: 'philosophical',
    backgroundColor: 0xFFFFF7E6,
    animatedGradient: [0xFFFFF7E6, 0xFFFDE3B0],
    textColor: 0xFF2A2218,
    accentColor: 0xFFE08A00,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'sunrise', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'utilitarisme': LightingProfile(
    id: 'utilitarisme',
    label: 'Utilitarisme',
    group: 'philosophical',
    backgroundColor: 0xFF0F172A,
    animatedGradient: [0xFF0F172A, 0xFF1E293B],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF22C55E,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'meter_slow', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'structuralisme': LightingProfile(
    id: 'structuralisme',
    label: 'Structuralisme',
    group: 'philosophical',
    backgroundColor: 0xFF111827,
    animatedGradient: [0xFF111827, 0xFF0B1220],
    textColor: 0xFFF9FAFB,
    accentColor: 0xFF38BDF8,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'lattice', periodSeconds: 30.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),
  'philosophies_orientales': LightingProfile(
    id: 'philosophies_orientales',
    label: 'Philosophies orientales',
    group: 'philosophical',
    backgroundColor: 0xFFF2F2F0,
    animatedGradient: [0xFFF2F2F0, 0xFFE6E6E0],
    textColor: 0xFF1E1E1E,
    accentColor: 0xFFA3A3A3,
    fontFamilyTitle: 'Literata',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'still', periodSeconds: 60.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 120),
  ),

  // ========================================
  // PHILOSOPHES
  // ========================================
  'socrate': LightingProfile(
    id: 'socrate',
    label: 'Socrate',
    group: 'philosopher',
    backgroundColor: 0xFFFFF7ED,
    animatedGradient: [0xFFFFF7ED, 0xFFFFE4C7],
    textColor: 0xFF2A2218,
    accentColor: 0xFFF59E0B,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'dialogue_ripple', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'platon': LightingProfile(
    id: 'platon',
    label: 'Platon',
    group: 'philosopher',
    backgroundColor: 0xFF0B1220,
    animatedGradient: [0xFF0B1220, 0xFF1E293B],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFA78BFA,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'cave_light', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'aristote': LightingProfile(
    id: 'aristote',
    label: 'Aristote',
    group: 'philosopher',
    backgroundColor: 0xFFF5F7FA,
    animatedGradient: [0xFFF5F7FA, 0xFFE2E8F0],
    textColor: 0xFF0B1220,
    accentColor: 0xFF64748B,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'taxonomy_lines', periodSeconds: 34.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'epicure': LightingProfile(
    id: 'epicure',
    label: 'Épicure',
    group: 'philosopher',
    backgroundColor: 0xFFEAF2FF,
    animatedGradient: [0xFFEAF2FF, 0xFFD8E7FF],
    textColor: 0xFF0B1220,
    accentColor: 0xFF60A5FA,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'garden_breeze', periodSeconds: 30.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'seneque': LightingProfile(
    id: 'seneque',
    label: 'Sénèque',
    group: 'philosopher',
    backgroundColor: 0xFFE8EFEA,
    animatedGradient: [0xFFE8EFEA, 0xFFD7E5DD],
    textColor: 0xFF1F2D26,
    accentColor: 0xFF3F6B55,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'still', periodSeconds: 60.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'epictete': LightingProfile(
    id: 'epictete',
    label: 'Épictète',
    group: 'philosopher',
    backgroundColor: 0xFFE8EFEA,
    animatedGradient: [0xFFE8EFEA, 0xFFD7E5DD],
    textColor: 0xFF1F2D26,
    accentColor: 0xFF2F5D47,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'still', periodSeconds: 50.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'marc_aurele': LightingProfile(
    id: 'marc_aurele',
    label: 'Marc Aurèle',
    group: 'philosopher',
    backgroundColor: 0xFFE8EFEA,
    animatedGradient: [0xFFE8EFEA, 0xFFD7E5DD],
    textColor: 0xFF1F2D26,
    accentColor: 0xFF1F4D3A,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'horizon', periodSeconds: 34.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'spinoza': LightingProfile(
    id: 'spinoza',
    label: 'Spinoza',
    group: 'philosopher',
    backgroundColor: 0xFFFDF2F8,
    animatedGradient: [0xFFFDF2F8, 0xFFFCE7F3],
    textColor: 0xFF2A1B3D,
    accentColor: 0xFFEC4899,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'geometric_wave', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'kant': LightingProfile(
    id: 'kant',
    label: 'Kant',
    group: 'philosopher',
    backgroundColor: 0xFFEEF0F5,
    animatedGradient: [0xFFEEF0F5, 0xFFE2E8F0],
    textColor: 0xFF0B1220,
    accentColor: 0xFF475569,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'grid_parallax', periodSeconds: 40.0),
    entrance: EntranceProfile(type: 'stepper_reveal', staggerMs: 130),
  ),
  'nietzsche': LightingProfile(
    id: 'nietzsche',
    label: 'Nietzsche',
    group: 'philosopher',
    backgroundColor: 0xFF120C10,
    animatedGradient: [0xFF120C10, 0xFF2A1220],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFFEF4444,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'pulse_heat', periodSeconds: 18.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'schopenhauer': LightingProfile(
    id: 'schopenhauer',
    label: 'Schopenhauer',
    group: 'philosopher',
    backgroundColor: 0xFF0B1220,
    animatedGradient: [0xFF0B1220, 0xFF111827],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF94A3B8,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'heavy_drift', periodSeconds: 34.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'kierkegaard': LightingProfile(
    id: 'kierkegaard',
    label: 'Kierkegaard',
    group: 'philosopher',
    backgroundColor: 0xFF1F2937,
    animatedGradient: [0xFF1F2937, 0xFF0B1220],
    textColor: 0xFFF9FAFB,
    accentColor: 0xFFFBBF24,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'oscillation', periodSeconds: 22.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'sartre': LightingProfile(
    id: 'sartre',
    label: 'Sartre',
    group: 'philosopher',
    backgroundColor: 0xFF0E1A2B,
    animatedGradient: [0xFF0E1A2B, 0xFF111827],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF6FA3FF,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'oscillation', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'camus': LightingProfile(
    id: 'camus',
    label: 'Camus',
    group: 'philosopher',
    backgroundColor: 0xFF111111,
    animatedGradient: [0xFF111111, 0xFF2B2B2B],
    textColor: 0xFFF5F5F5,
    accentColor: 0xFFFFD166,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'glitch_soft', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'simone_de_beauvoir': LightingProfile(
    id: 'simone_de_beauvoir',
    label: 'Simone de Beauvoir',
    group: 'philosopher',
    backgroundColor: 0xFF111827,
    animatedGradient: [0xFF111827, 0xFF0B1220],
    textColor: 0xFFF9FAFB,
    accentColor: 0xFFF472B6,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'spotlight_sweep', periodSeconds: 30.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'hannah_arendt': LightingProfile(
    id: 'hannah_arendt',
    label: 'Hannah Arendt',
    group: 'philosopher',
    backgroundColor: 0xFF0F172A,
    animatedGradient: [0xFF0F172A, 0xFF1E293B],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF22C55E,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'lattice', periodSeconds: 30.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'confucius': LightingProfile(
    id: 'confucius',
    label: 'Confucius',
    group: 'philosopher',
    backgroundColor: 0xFFF6F1E8,
    animatedGradient: [0xFFF6F1E8, 0xFFEFE5D7],
    textColor: 0xFF1E1A14,
    accentColor: 0xFFB89B5E,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'vertical_glow', periodSeconds: 30.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'montaigne': LightingProfile(
    id: 'montaigne',
    label: 'Montaigne',
    group: 'philosopher',
    backgroundColor: 0xFFF5EDE3,
    animatedGradient: [0xFFF5EDE3, 0xFFE8D9C8],
    textColor: 0xFF2A2218,
    accentColor: 0xFF92400E,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'soft_drift', periodSeconds: 32.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'diogene': LightingProfile(
    id: 'diogene',
    label: 'Diogène',
    group: 'philosopher',
    backgroundColor: 0xFFFFF7E6,
    animatedGradient: [0xFFFFF7E6, 0xFFFDE3B0],
    textColor: 0xFF2A2218,
    accentColor: 0xFFF59E0B,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'glitch_soft', periodSeconds: 20.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'rousseau': LightingProfile(
    id: 'rousseau',
    label: 'Rousseau',
    group: 'philosopher',
    backgroundColor: 0xFFE8F5E9,
    animatedGradient: [0xFFE8F5E9, 0xFFC8E6C9],
    textColor: 0xFF1B5E20,
    accentColor: 0xFF4CAF50,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'garden_breeze', periodSeconds: 26.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'hume': LightingProfile(
    id: 'hume',
    label: 'Hume',
    group: 'philosopher',
    backgroundColor: 0xFFECEFF1,
    animatedGradient: [0xFFECEFF1, 0xFFCFD8DC],
    textColor: 0xFF263238,
    accentColor: 0xFF607D8B,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'raindrop_slow', periodSeconds: 28.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'foucault': LightingProfile(
    id: 'foucault',
    label: 'Foucault',
    group: 'philosopher',
    backgroundColor: 0xFF1A1A2E,
    animatedGradient: [0xFF1A1A2E, 0xFF16213E],
    textColor: 0xFFF2F4F8,
    accentColor: 0xFF8B5CF6,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'lattice', periodSeconds: 24.0),
    entrance: EntranceProfile(type: 'layer_fade', staggerMs: 130),
  ),
  'descartes': LightingProfile(
    id: 'descartes',
    label: 'Descartes',
    group: 'philosopher',
    backgroundColor: 0xFFF5F7FA,
    animatedGradient: [0xFFF5F7FA, 0xFFE2E8F0],
    textColor: 0xFF0B1220,
    accentColor: 0xFF3B82F6,
    fontFamilyTitle: 'PlayfairDisplay',
    fontFamilyBody: 'Charter',
    motion: MotionProfile(type: 'grid_parallax', periodSeconds: 36.0),
    entrance: EntranceProfile(type: 'stepper_reveal', staggerMs: 130),
  ),
};

/// Get a lighting profile by approach key, with fallback to default
LightingProfile getLightingProfile(String approachKey) {
  return kLightingProfilesMap[approachKey] ?? kDefaultLightingProfile;
}
