default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: File.read("fastlane/AuthKey.p8"),
      in_house: false
    )

    match(
      type: "appstore",
      git_basic_authorization: Base64.strict_encode64("#{ENV['GH_PAT']}:x-oauth-basic"),
      api_key: api_key,
      readonly: is_ci
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: ENV["APPLE_TEAM_ID"],
      profile_name: ENV["sigh_com.unautreregard.app.en_appstore_profile-name"],
      code_sign_identity: "iPhone Distribution"
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.unautreregard.app.en" => ENV["sigh_com.unautreregard.app.en_appstore_profile-name"]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
